services:
  - type: web
    name: orange-app
    env: docker
    plan: free

    dockerfilePath: ./server/Dockerfile

    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 10000

      - key: DB_PATH
        value: /tmp/orange.db

      - key: UPLOAD_DIR
        value: /tmp/uploads

      - key: CLIENT_ORIGIN
        value: https://orange-app.onrender.com

      - key: JWT_SECRET
        generateValue: true

    startCommand: sh -c "node src/seed.js && node src/index.js"
